// Real-like sample data for unified charts testing
export const testingChartsData = {
  bar: {
    standard: [
      { month: "Jan", revenue: 125000 },
      { month: "Feb", revenue: 142000 },
      { month: "Mar", revenue: 138000 },
      { month: "Apr", revenue: 165000 },
      { month: "May", revenue: 158000 },
      { month: "Jun", revenue: 182000 },
    ],
    multiple: [
      { month: "Jan", desktop: 12500, mobile: 8200, tablet: 3100 },
      { month: "Feb", desktop: 14200, mobile: 9500, tablet: 3800 },
      { month: "Mar", desktop: 13800, mobile: 8800, tablet: 3500 },
      { month: "Apr", desktop: 16500, mobile: 11200, tablet: 4200 },
    ],
    stacked: [
      { quarter: "Q1", product: 85000, service: 42000, support: 18000 },
      { quarter: "Q2", product: 92000, service: 48000, support: 22000 },
      { quarter: "Q3", product: 105000, service: 52000, support: 25000 },
      { quarter: "Q4", product: 118000, service: 58000, support: 28000 },
    ],
    negative: [
      { month: "Jan", profit: -15000 },
      { month: "Feb", profit: 25000 },
      { month: "Mar", profit: -8000 },
      { month: "Apr", profit: 35000 },
    ],
  },
  pie: {
    default: [
      { source: "Direct Traffic", visitors: 28450 },
      { source: "Organic Search", visitors: 19800 },
      { source: "Social Media", visitors: 15600 },
      { source: "Email Campaigns", visitors: 12400 },
      { source: "Referral", visitors: 8900 },
    ],
    label: [
      { product: "Software Licenses", revenue: 2850000 },
      { product: "Cloud Services", revenue: 4200000 },
      { product: "Consulting", revenue: 1850000 },
      { product: "Training", revenue: 950000 },
    ],
    donut: [
      { region: "North America", sales: 2850000 },
      { region: "Europe", sales: 1980000 },
      { region: "Asia Pacific", sales: 1650000 },
      { region: "Latin America", sales: 850000 },
    ],
    interactive: [
      { company: "Microsoft", share: 32.5 },
      { company: "Amazon", share: 28.7 },
      { company: "Google", share: 18.2 },
      { company: "Oracle", share: 12.1 },
      { company: "Others", share: 8.5 },
    ],
  },
  radar: {
    default: [
      { skill: "Technical Skills", score: 92 },
      { skill: "Problem Solving", score: 88 },
      { skill: "Communication", score: 85 },
      { skill: "Leadership", score: 78 },
      { skill: "Creativity", score: 82 },
      { skill: "Teamwork", score: 90 },
    ],
    linesOnly: [
      { metric: "Performance", value: 94 },
      { metric: "Reliability", value: 89 },
      { metric: "Efficiency", value: 87 },
      { metric: "Innovation", value: 82 },
      { metric: "Cost Effectiveness", value: 91 },
      { metric: "User Experience", value: 88 },
    ],
    multiple: [
      { category: "Sales", teamA: 95, teamB: 87, teamC: 92 },
      { category: "Marketing", teamA: 78, teamB: 92, teamC: 85 },
      { category: "Support", teamA: 85, teamB: 79, teamC: 88 },
      { category: "Development", teamA: 92, teamB: 95, teamC: 90 },
      { category: "Design", teamA: 88, teamB: 84, teamC: 93 },
      { category: "Operations", teamA: 90, teamB: 88, teamC: 87 },
    ],
  },
  radial: {
    default: [
      { month: "January", visitors: 28450 },
      { month: "February", visitors: 31200 },
      { month: "March", visitors: 29800 },
      { month: "April", visitors: 34500 },
      { month: "May", visitors: 31800 },
      { month: "June", visitors: 32500 },
    ],
    stacked: [
      { quarter: "Q1", sales: 2850000, marketing: 850000, support: 420000 },
      { quarter: "Q2", sales: 3120000, marketing: 920000, support: 480000 },
      { quarter: "Q3", sales: 2980000, marketing: 880000, support: 450000 },
      { quarter: "Q4", sales: 3450000, marketing: 1050000, support: 520000 },
    ],
    progress: [{ category: "Goal Progress", progress: 87 }],
  },
  line: {
    default: [
      { month: "Jan", visitors: 28450 },
      { month: "Feb", visitors: 31200 },
      { month: "Mar", visitors: 29800 },
      { month: "Apr", visitors: 34500 },
      { month: "May", visitors: 31800 },
      { month: "Jun", visitors: 32500 },
    ],
    linear: [
      { hour: "00:00", performance: 95 },
      { hour: "06:00", performance: 87 },
      { hour: "12:00", performance: 92 },
      { hour: "18:00", performance: 89 },
    ],
    step: [
      { time: "00:00", status: 100 },
      { time: "04:00", status: 100 },
      { time: "08:00", status: 95 },
      { time: "12:00", status: 95 },
      { time: "16:00", status: 100 },
    ],
    multiple: [
      { month: "Jan", desktop: 12500, mobile: 8200, tablet: 3100 },
      { month: "Feb", desktop: 14200, mobile: 9500, tablet: 3800 },
      { month: "Mar", desktop: 13800, mobile: 8800, tablet: 3500 },
      { month: "Apr", desktop: 16500, mobile: 11200, tablet: 4200 },
    ],
    dots: [
      { quarter: "Q1", value: 85 },
      { quarter: "Q2", value: 92 },
      { quarter: "Q3", value: 88 },
      { quarter: "Q4", value: 95 },
    ],
    label: [
      { rep: "John Smith", sales: 125000 },
      { rep: "Sarah Johnson", sales: 142000 },
      { rep: "Mike Davis", sales: 138000 },
      { rep: "Lisa Wilson", sales: 165000 },
    ],
  },
  area: {
    standard: [
      { month: "Jan", revenue: 125000 },
      { month: "Feb", revenue: 142000 },
      { month: "Mar", revenue: 138000 },
      { month: "Apr", revenue: 165000 },
      { month: "May", revenue: 158000 },
      { month: "Jun", revenue: 182000 },
    ],
    linear: [
      { hour: "00:00", performance: 95 },
      { hour: "06:00", performance: 87 },
      { hour: "12:00", performance: 92 },
      { hour: "18:00", performance: 89 },
    ],
    step: [
      { time: "00:00", status: 100 },
      { time: "04:00", status: 100 },
      { time: "08:00", status: 95 },
      { time: "12:00", status: 95 },
      { time: "16:00", status: 100 },
    ],
    stacked: [
      { quarter: "Q1", product: 85000, service: 42000, support: 18000 },
      { quarter: "Q2", product: 92000, service: 48000, support: 22000 },
      { quarter: "Q3", product: 105000, service: 52000, support: 25000 },
      { quarter: "Q4", product: 118000, service: 58000, support: 28000 },
    ],
  },
};

// Chart configurations for each type
export const chartConfigs = {
  bar: {
    standard: {
      type: "bar-standard" as const,
      title: "Monthly Revenue",
      description: "Revenue for the last 6 months",
      dataKey: "revenue",
      data: testingChartsData.bar.standard,
    },
    multiple: {
      type: "bar-multiple" as const,
      title: "Desktop vs Mobile Traffic",
      groupedKeys: ["desktop", "mobile", "tablet"],
      color: ["hsl(var(--primary))", "hsl(var(--secondary))", "hsl(var(--accent))"],
      data: testingChartsData.bar.multiple,
    },
    stacked: {
      type: "bar-stacked" as const,
      title: "Revenue Breakdown",
      groupedKeys: ["product", "service", "support"],
      data: testingChartsData.bar.stacked,
    },
    negative: {
      type: "bar-negative" as const,
      title: "Profit/Loss Analysis",
      negativeColor: "hsl(var(--destructive))",
      data: testingChartsData.bar.negative,
    },
  },
  pie: {
    default: {
      type: "pie-standard" as const,
      title: "Website Traffic Sources",
      description: "Distribution of traffic by source",
      dataKey: "visitors",
      nameKey: "source",
      data: testingChartsData.pie.default,
    },
    label: {
      type: "pie-label" as const,
      title: "Revenue by Product",
      description: "Product revenue distribution with labels",
      dataKey: "revenue",
      nameKey: "product",
      showLabels: true,
      data: testingChartsData.pie.label,
    },
    donut: {
      type: "pie-donut" as const,
      title: "Sales by Region",
      description: "Regional sales distribution",
      dataKey: "sales",
      nameKey: "region",
      data: testingChartsData.pie.donut,
    },
    interactive: {
      type: "pie-interactive" as const,
      title: "Cloud Market Share",
      description: "Market share of major cloud providers",
      dataKey: "share",
      nameKey: "company",
      data: testingChartsData.pie.interactive,
      activeIndex: 0, // This will be overridden in the component
    },
  },
  radar: {
    default: {
      type: "radar-standard" as const,
      title: "Skills Assessment",
      description: "Employee skill levels across different areas",
      dataKey: "score",
      nameKey: "skill",
      data: testingChartsData.radar.default,
    },
    linesOnly: {
      type: "radar-lines-only" as const,
      title: "Performance Metrics",
      description: "Key performance indicators without fill",
      dataKey: "value",
      nameKey: "metric",
      strokeWidth: 3,
      color: "hsl(217, 91%, 60%)",
      data: testingChartsData.radar.linesOnly,
    },
    multiple: {
      type: "radar-multiple" as const,
      title: "Team Comparison",
      description: "Comparing performance across different teams",
      nameKey: "category",
      groupedKeys: ["teamA", "teamB", "teamC"],
      data: testingChartsData.radar.multiple,
    },
  },
  radial: {
    default: {
      type: "radial-standard" as const,
      title: "Website Visitors",
      description: "Monthly visitor distribution",
      dataKey: "visitors",
      nameKey: "month",
      centerText: 192250,
      centerLabel: "Total Visitors",
      data: testingChartsData.radial.default,
    },
    stacked: {
      type: "radial-stacked" as const,
      title: "Revenue Breakdown",
      description: "Quarterly revenue by department",
      nameKey: "quarter",
      groupedKeys: ["sales", "marketing", "support"],
      showLegend: true,
      data: testingChartsData.radial.stacked,
    },
    progress: {
      type: "radial-standard" as const,
      title: "Goal Progress",
      dataKey: "progress",
      centerText: "87%",
      centerLabel: "Complete",
      color: "hsl(142, 76%, 36%)",
      data: testingChartsData.radial.progress,
    },
  },
  line: {
    default: {
      type: "line-standard" as const,
      title: "Website Traffic",
      description: "Monthly visitors over time",
      dataKey: "visitors",
      data: testingChartsData.line.default,
    },
    linear: {
      type: "line-linear" as const,
      title: "System Performance",
      dataKey: "performance",
      strokeWidth: 3,
      data: testingChartsData.line.linear,
    },
    step: {
      type: "line-step" as const,
      title: "Server Status Changes",
      description: "Status transitions over time",
      dataKey: "status",
      color: "hsl(142, 76%, 36%)",
      data: testingChartsData.line.step,
    },
    multiple: {
      type: "line-multiple" as const,
      title: "Traffic Sources",
      groupedKeys: ["desktop", "mobile", "tablet"],
      data: testingChartsData.line.multiple,
    },
    dots: {
      type: "line-dots" as const,
      title: "Quarterly Performance",
      description: "Key metrics with highlighted data points",
      dataKey: "value",
      dotSize: 6,
      activeDotSize: 8,
      color: "hsl(217, 91%, 60%)",
      data: testingChartsData.line.dots,
    },
    label: {
      type: "line-label" as const,
      title: "Sales Performance",
      description: "Revenue with visible values",
      dataKey: "sales",
      customLabel: (value: any) => `$${(value / 1000).toFixed(0)}K`,
      data: testingChartsData.line.label,
    },
  },
  area: {
    standard: {
      type: "area-standard" as const,
      title: "Revenue Trend",
      description: "Revenue over time with filled area",
      dataKey: "revenue",
      data: testingChartsData.area.standard,
    },
    linear: {
      type: "area-linear" as const,
      title: "System Performance",
      dataKey: "performance",
      strokeWidth: 3,
      data: testingChartsData.area.linear,
    },
    step: {
      type: "area-step" as const,
      title: "Server Status",
      description: "Status changes over time",
      dataKey: "status",
      color: "hsl(142, 76%, 36%)",
      data: testingChartsData.area.step,
    },
    stacked: {
      type: "area-stacked" as const,
      title: "Revenue Breakdown",
      groupedKeys: ["product", "service", "support"],
      data: testingChartsData.area.stacked,
    },
  },
};

// Chart type information for quick reference
export const chartTypeInfo = {
  bar: {
    title: "Bar Charts",
    description: "Vertical and horizontal bar visualizations",
    types: [
      { type: "bar-standard", name: "Standard Bar", description: "Basic vertical bar chart" },
      { type: "bar-multiple", name: "Multiple Bar", description: "Side-by-side comparison" },
      { type: "bar-stacked", name: "Stacked Bar", description: "Part-to-whole relationships" },
      { type: "bar-negative", name: "Negative Bar", description: "Positive and negative values" },
    ],
  },
  pie: {
    title: "Pie Charts",
    description: "Circular data visualizations",
    types: [
      { type: "pie-standard", name: "Standard Pie", description: "Basic pie chart" },
      { type: "pie-label", name: "Label Pie", description: "With percentage labels" },
      { type: "pie-donut", name: "Donut Chart", description: "With center total" },
      { type: "pie-interactive", name: "Interactive Pie", description: "With hover effects" },
    ],
  },
  radar: {
    title: "Radar Charts",
    description: "Polar coordinate visualizations",
    types: [
      { type: "radar-standard", name: "Standard Radar", description: "Filled areas with dots" },
      { type: "radar-lines-only", name: "Lines Only", description: "Clean lines without fill" },
      { type: "radar-multiple", name: "Multiple Radar", description: "Compare multiple series" },
    ],
  },
  radial: {
    title: "Radial Charts",
    description: "Circular bar visualizations",
    types: [
      {
        type: "radial-standard",
        name: "Standard Radial",
        description: "Single series with center text",
      },
      { type: "radial-stacked", name: "Stacked Radial", description: "Multiple series in layers" },
    ],
  },
  line: {
    title: "Line Charts",
    description: "Time series and trend visualizations",
    types: [
      { type: "line-standard", name: "Standard Line", description: "Natural curves" },
      { type: "line-linear", name: "Linear Line", description: "Sharp angles" },
      { type: "line-step", name: "Step Line", description: "Flat segments" },
      { type: "line-multiple", name: "Multiple Line", description: "Compare multiple series" },
      { type: "line-dots", name: "Dots Line", description: "Emphasize data points" },
      { type: "line-label", name: "Label Line", description: "Show data values" },
    ],
  },
  area: {
    title: "Area Charts",
    description: "Filled area visualizations",
    types: [
      {
        type: "area-standard",
        name: "Standard Area",
        description: "Filled area with natural curves",
      },
      { type: "area-linear", name: "Linear Area", description: "Sharp angles with fill" },
      { type: "area-step", name: "Step Area", description: "Flat segments with fill" },
      { type: "area-stacked", name: "Stacked Area", description: "Multiple series stacked" },
    ],
  },
};
